-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 19, 2021 at 04:24 PM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `universe`
--

-- --------------------------------------------------------

--
-- Table structure for table `characters`
--

CREATE TABLE `characters` (
  `id` int(4) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `image1` varchar(2083) NOT NULL,
  `image2` varchar(2083) NOT NULL,
  `played_by` varchar(50) NOT NULL,
  `universe` varchar(50) NOT NULL,
  `uni_char` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `characters`
--

INSERT INTO `characters` (`id`, `name`, `description`, `image1`, `image2`, `played_by`, `universe`, `uni_char`) VALUES
(1, 'Steve Rogers', 'Recipient of the Super Soldier serum, World War II hero Steve Rogers fights for American ideals as one of the world’s mightiest heroes and the leader of the Avengers. Also, the very first Avenger', 'https://cdn.goliath.com/eyJidWNrZXQiOiJwdWItc3RvcmFnZSIsImtleSI6ImdvbGlhdGgvd3AtY29udGVudC91cGxvYWRzLzIwMTYvMDUvQ2FwdGFpbi1BbWVyaWNhLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6Mjg4MCwiaGVpZ2h0IjoxODAwLCJmaXQiOiJjb3ZlciIsImJhY2tncm91bmQiOnsiciI6MCwiZyI6MCwiYiI6MCwiYWxwaGEiOjF9LCJwb3NpdGlvbiI6InRvcCJ9fX0=', 'https://images.thedirect.com/media/article_full/Captain_America_Best_Quotes_QyplfR7_ehD7DlZ.jpg', 'Chris Evans', 'MCU', 'Captain America'),
(2, 'Tony Stark', 'Tony Stark, a billionaire industrialist and genius inventor who is kidnapped and forced to build a devastating weapon. Instead, using his intelligence and ingenuity, Tony builds a high-tech suit of armor and escapes captivity. When he uncovers a nefarious plot with global implications, he dons his powerful armor and vows to protect the world as Iron Man.', 'https://images.hindustantimes.com/rf/image_size_630x354/HT/p2/2019/05/08/Pictures/_856c127e-7171-11e9-9308-6ffbdc5c45a7.jpeg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy7h0974bNbnfRZvYvOjI6VJY6tIeiHocA_QFillhqtDOlHDPp1I8FopDHgegcadDi1ZQ&usqp=CAU', 'Robert Downey Junior', 'MCU', 'Iron man'),
(3, 'Bruce Banner', 'Exposed to heavy doses of gamma radiation, scientist Bruce Banner transforms into the mean, green rage machine called the Hulk. Dr. Bruce Banner lives a life caught between the soft-spoken scientist he’s always been and the uncontrollable green monster powered by his rage. ', 'https://c4.wallpaperflare.com/wallpaper/650/931/817/avengers-hulk-incredible-hulk-illustration-wallpaper-preview.jpg', 'https://i0.wp.com/straightfromamovie.com/wp-content/uploads/2017/04/Hulk.jpg?resize=805%2C452&ssl=1', 'Edward Norton, Mark Ruffalo', 'MCU', 'Incredible Hulk'),
(4, 'Thor Odinson', 'Thor Odinson wields the power of the ancient Asgardians to fight evil throughout the Nine Realms and beyond. The son of Odin uses his mighty abilities as the God of Thunder to protect his home Asgard ', 'https://vistapointe.net/images/thor-2.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNHe9QZ5gr7kAJnIsv8Ot2x2pzpypxHvF8Kg&usqp=CAU', 'Chris Hemsworth', 'MCU', 'Thor'),
(5, 'Natasha Romanoff', 'A deadly assassin is closing in on Natasha Romanoff. Now Natasha must reunite with an unlikely group of spies from her past in order to survive and stop a lethal force from being unleashed on the world', 'https://images4.alphacoders.com/107/thumb-1920-1070325.jpg', 'https://supertabthemes.com/wp-content/uploads/2020/03/8.jpg', 'Scarlett Johansson', 'MCU', 'Black Widow'),
(6, 'Clinton Francis/Clint Barton\r\n', 'Clint Barton also known by his alter ego Hawkeye and briefly as the Ronin, is a former S.H.I.E.L.D. agent and a founding member of the Avengers with the abilities of an expert marksman and hand-to-hand combatant, with his preferred weapon being a compound bow and a variety of trick arrows', 'https://c4.wallpaperflare.com/wallpaper/264/626/432/hawkeye-the-avengers-jeremy-renner-clint-barton-wallpaper-thumb.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZlT2sxlHrmxoEyzvIaMs-Kp8uY8kr4bc2owhSi8RIZNsyAQ3ool4wjP6xs96ZJ75sTWc&usqp=CAU', 'Jeremy Renner', 'MCU', 'Hawkeye'),
(7, 'Wanda Maximoff', 'Scarlet Witch, is a member of the Avengers with hypnosis and telekinesis abilities obtained from the Mind Stone, and chaos magic powers that she has had since birth. Based on the Marvel Comics character of the same name created by Stan Lee and Jack Kirby. She is the twin sister of Pietro Maximoff. In 2015, she becomes a member of the Avengers. In 2016, she develops a romantic relationship with Vision.[39][40][41] In 2018, she is a victim of the Blip. In 2023, she is restored to life and learns her true nature as the Scarlet Witch', 'https://wallpaperaccess.com/full/1089839.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6kU-jypITQzdMytIYAbrrUo6PeHKIZFQ6hGsI-M-ZGpbMdfi8xuhlXfdeaS21-Xe768E&usqp=CAU', 'Elizabeth Olsen', 'MCU', 'Scarlet Witch'),
(8, 'Vision', 'The Vision, Introduced in Avengers: Age of Ultron (2015), Vision is an android (or \"synthezoid\") created by the robotic villain Ultron to serve as his organic body. However, he is recovered by the Avengers and brought to sentience by Tony Stark and Bruce Banner, who upload the core software of Stark\'s AI, J.A.R.V.I.S., into the vibranium body constructed by Ultron, with energy provided by Thor. Vision subsequently joins the Avengers and develops a romantic relationship with his teammate, Wanda Maximoff. Most of Vision\'s powers stem from the Mind Stone in his forehead, which is also what keeps him alive.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIh2R15aB8A5Vnx4pbfxToiBOLwMgKHn-edqGNABAoWifFuMr5XTAkmAkUl2AD8shFR_M&usqp=CAU', 'https://c4.wallpaperflare.com/wallpaper/980/286/462/the-vision-marvel-cinematic-universe-avengers-age-of-ultron-paul-bettany-wallpaper-thumb.jpg', 'Paul Bettany', 'MCU', 'Vision'),
(9, 'James (Rhodey) Rhodes', 'Is an Avenger and lieutenant colonel in the United States Air Force where he operates the War Machine armor and acts as the military\'s chief liaison to Stark Industries\' weapons division.[53][54][55] Rhodes is a close confidant of Tony Stark\'s and from that relationship, he eventually becomes a major member of the Avengers. During the events of Iron Man 3, the War Machine armor is briefly renamed Iron Patriot', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROdyVmSnIP0onhVJxDL_pZR_pCUAZg3evlk8XaAEojCNXdilX39U0N-aTO1iZ8rRPq-eo&usqp=CAU', 'https://i.pinimg.com/originals/5b/77/f4/5b77f4734ec7d0dfd6e3bf08cad2e5fd.jpg', 'Terrence Howard, Don Cheadle', 'MCU', 'War Machine'),
(10, 'Samuel Thomas Wilson', 'As the superhero Falcon, Wilson uses mechanical wings to fly, and has limited telepathic and empathic control over birds. Following Steve Rogers\'s retirement, Wilson becomes the newest Captain America in All-New Captain America #1 (Jan. 2015) and leader of the Avengers. Wilson\'s deceased nephew was the Incredible Hulk\'s sometime-sidekick Jim Wilson, one of the first openly HIV-positive comic-book characters. Jim Wilson\'s father Gideon Wilson would go on to join the Gamma Corps. ', 'https://wallpaperaccess.com/full/3100223.jpg', 'https://www.rvcj.com/wp-content/uploads/2019/09/falcon-in-avengers-endgame.jpg', 'Anthony Mackie', 'MCU', 'Falcon'),
(11, 'Peter Parker', 'Spider-Man, is an Avenger and high school teenager who received spider-like abilities after being bitten by a radioactive spider. He first appears in Captain America: Civil War, although his introduction was later retconned as a child who wore an Iron Man helmet mask in Iron Man 2. He is later depicted as a protégé of Tony Stark. In 2018, he becomes an Avenger and falls victim to the Blip. In 2023, he is restored to life', 'https://assets2.ignimgs.com/2014/06/06/amazing-spider-man-movie-posterjpg-18998d_160w.jpg?width=1280', 'https://hips.hearstapps.com/digitalspyuk.cdnds.net/17/26/1498474030-spider-man-homecoming.jpg', 'Tom Holland', 'MCU', 'Spiderman'),
(12, 'Rocket', 'Rocket is an Avenger and member of the Guardians of the Galaxy who is a hot-tempered Halfworlder mercenary and master of weapons.[56] Rocket was based on movement from Sean Gunn and also real-life behavior of an actual raccoon called Oreo.[57] In 2018, he survives the Blip and due to his friendship with Thor, becomes a member of the Avengers', 'https://vistapointe.net/images/rocket-raccoon-4.jpg', 'https://cdn.wallpapersafari.com/8/84/Cad7KJ.jpg', 'Bradley Cooper', 'MCU', 'Rocket Raccoon'),
(13, 'Nebula', 'Nebula is an Avenger, member of the Guardians of the Galaxy and former lieutenant of Thanos, who raised her as his daughter along with Gamora. Nebula was created by Roger Stern and John Buscema and first appears in the film Guardians of the Galaxy as a secondary antagonist within the film but in later appearances she is portrayed as more sympathetic. Eventually, Nebula teams up with the Guardians of the Galaxy and then joins the Avengers to defeat her foster father. Though the current version of her joins the Avengers, a past version allies with Thanos to stop the Avengers. This is due to fear, causing the present Nebula to have to kill her past counterpart', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgd9-FUJ5uD8v4aCcX1dT8seczsBDl3kkkDS2ah02aaKV6jy_fjeVZ3-y3NdM2leSnw-w&usqp=CAU', 'https://c4.wallpaperflare.com/wallpaper/723/196/1021/the-avengers-avengers-endgame-avengers-endgame-karen-gillan-nebula-marvel-comics-hd-wallpaper-preview.jpg', 'Karen Gillan', 'MCU', 'Nebula'),
(14, 'Carol Danvers', 'Captain Marvel, is a former Air Force test pilot who acquired cosmic energy force powers from the Tesseract after an explosion that wiped out her memory. The Kree decided to keep her as their own as a weapon against the Skrulls. In 1995, she traced her true origins to Earth where she met and befriended Nick Fury before leaving for space with the Skrulls. In 2018, following the Blip, she returns to Earth and by 2023, has joined the Avengers', 'https://wallpaperaccess.com/full/1482515.jpg', 'https://i.pinimg.com/originals/ec/02/74/ec02741e71610b548faeff9a4550ce22.jpg', 'Brie Larson', 'MCU', 'Captain Marvel'),
(15, 'Okoye', 'is a Wakandan warrior and the general of the Dora Milaje. She fights on T\'Challa\'s side when N\'Jadaka plots to usurp the throne and fights alongside the Avengers to combat Thanos and his army', 'https://wallpapercave.com/wp/wp6608370.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPjWBFaU6kxYFjT1NwocqKdzK3Ldrwttyuey4yY13bHciYHeZTqeYY1rQ2dYSGEpaikxQ&usqp=CAU', 'Danai Gurira', 'MCU', 'Okoye'),
(16, 'Scott Lang', 'Ant-Man, is an Avenger and former petty criminal who acquired a suit from Hank Pym that allows him to shrink or grow in scale while also increasing in strength, as well as the ability to communicate with different species of ants. He is also the father of Cassie Lang. In 2018, he helps Pym and his daughter Hope van Dyne (his love interest) release Janet van Dyne from the Quantum Realm. He is later stranded in the Realm. In 2023, he is released and joins the Avengers to reverse the Blip', 'http://4.bp.blogspot.com/-stPDmc60j7A/Vbppi1jDfiI/AAAAAAAAQeM/DsrykSLZvG4/s640/ant-man.jpg', 'http://cdn.wegotthiscovered.com/wp-content/uploads/2017/12/ant-man-wasp-san-diego-comic-con-2017-pointofgeeks.jpg', 'Paul Rudd', 'MCU', 'Ant Man'),
(17, 'T\'Challa', 'T\'Challa is the protector of Wakanda, known as the Black Panther, a highly skilled warrior who gains enhanced strength and agility by ingesting the vibranium-enriched heart-shaped herb. Following the death of his father, T\'Challa ascends the throne and becomes the king of Wakanda. His suit is also made of vibranium. After the death of Boseman, Kevin Feige announced that the character would not be recast for the upcoming Black Panther sequel, leaving T\'Challa in a shroud of mystery', 'https://wallpaperaccess.com/full/54038.png', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSjInG6WcJBHzU9JTIxs_C4l5STfFWtcioMqJxIQ3YI5wDssCYTAPKkSYUFS2RhJm1Eh4&usqp=CAU', 'Chadwick Boseman', 'MCU', 'Black Panther'),
(18, 'Dr. Stephen Strange ', 'Dr. Stephen Strange known also by his academic title as Doctor Strange, is a powerful sorcerer and former neurosurgeon who, after a car accident that led to a journey of healing, discovered the hidden world of magic and alternate dimensions and became a Master of the Mystic Arts and the guardian of the Sanctum Sanctorum. In 2018, Strange is a victim of the Blip. In 2023, he is restored to life', 'https://wallpaperaccess.com/full/621124.jpg', 'https://media.comicbook.com/2016/07/doctor-strange-art-191572.jpg', 'Benedict Cumberbatch', 'MCU', 'Doctor Strange'),
(19, 'Nicholas Joseph (Nick) Fury', 'Nick Fury is the former director of S.H.I.E.L.D. and is responsible for the formation of the Avengers. Fury first appears in the MCU in the film Iron Man in a post-credits scene cameo.[26][27] In 2018, Fury falls victim to the Blip, but is restored to life in 2023 and attends Tony Stark\'s funeral. He later goes on \"vacation\" on a Skrull spaceship while his role is assumed by Talos on Earth', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvsdFzvzKU-d3RoKnsMTBp3GizXb2BFbdEAJwgVTT0GF1HzHXeWPB1UhkRECCz86ZgUBY&usqp=CAU', 'https://wallpaperaccess.com/full/1646512.jpg', 'Samuel L. Jackson', 'MCU', 'Nick Fury'),
(20, 'Loki Laufeyson', 'Loki Odinson and by his title as the God of Mischief,[33][34] is an Asgardian prince and warrior inspired by the Norse mythological deity of the same name. As in the comics, Loki has generally been a villain in the MCU, variously attempting to conquer Asgard or Earth, and having allied himself with more powerful villains to achieve his aims. He has particular antagonism for his adoptive brother Thor, and is known to variously ally with and then betray Thor and others, and regularly return from apparent death. Later on in his development in the films, he becomes less of a supervillain and more of an anti-hero.[35] Following his death at the hands of Thanos in 2018, an alternate version of him from 2012 appears in Avengers: Endgame taking the Tesseract. The character is often noted as being a fan favorite.', 'https://wallpaperaccess.com/full/480606.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1wtUpeBeQYmNi94kMxUc2_r0huvfBg7QbpGN5GP0ZiNRiPeZXWu8TIkLKFAulC-E308U&usqp=CAU', 'Tom Hiddleston', 'MCU', 'Loki'),
(21, 'Groot', 'Groot is the name of a tree-like humanoid (Flora colossus) and member of the Guardians of the Galaxy.[29] He has a limited vocabulary, using only his popular catchphrase \"I am Groot\", although he later managed to say the phrase \"We are Groot\" before sacrificing his life for the Guardians of the Galaxy in the battle with Ronan for the Power Stone', 'https://c4.wallpaperflare.com/wallpaper/764/505/66/baby-groot-4k-hd-superheroes-wallpaper-preview.jpg', 'https://i.pinimg.com/originals/f8/26/39/f82639049c577f8c1366b513c9930faa.jpg', 'Vin Diesel', 'MCU', 'Groot'),
(22, 'Bruce Wayne', 'Batman is the alias of Bruce Wayne, a wealthy American playboy, philanthropist, and industrialist who resides in Gotham City. Batman\'s origin story features him swearing vengeance against criminals after witnessing the murder of his parents Thomas and Martha, a vendetta tempered with the ideal of justice. He trains himself physically and intellectually, crafts a bat-inspired persona, and monitors the Gotham streets at night. Kane, Finger, and other creators accompanied Batman with supporting characters, including his sidekick Robin; allies Alfred Pennyworth, James Gordon, and Catwoman; and foes such as the Penguin, the Riddler, Two-Face, and his archenemy, the Joker', 'https://www.technocrazed.com/wp-content/uploads/2015/11/batman-logo-wallpaper-for-desktop-1080p-136.jpg', 'https://cdn.wallpapersafari.com/95/32/hRXGVI.jpg', 'Lewis G. Wilson, Adam West, Michael Keaton, Val Ki', 'DC', 'Batman'),
(23, 'Clark Joseph Kent/ Kal-El', 'Superman was born on the fictional planet Krypton and was named Kal-El. As a baby, his parents sent him to Earth in a small spaceship moments before Krypton was destroyed in a natural cataclysm. His ship landed in the American countryside, near the fictional town of Smallville. He was found and adopted by farmers Jonathan and Martha Kent, who named him Clark Kent. Clark developed various superhuman abilities, such as incredible strength and impervious skin. His adoptive parents advised him to use his abilities for the benefit of humanity, and he decided to fight crime. To protect his personal life, he changes into a colorful costume and uses the alias \"Superman\" when fighting crime. Clark resides in the fictional American city of Metropolis, where he works as a journalist for the Daily Planet', 'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700543221.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiqxmsFGvEGDL6Zf_q489slZE7cZOCmbEpdA&usqp=CAU', 'Christopher Reeve,Brandon Routh, Henry Cavill', 'DC', 'Superman'),
(24, 'Diana', 'In Wonder Woman, the Amazon princess Diana sets out to stop World War I, believing the conflict was started by the longtime enemy of the Amazons, Ares, after American pilot and spy Steve Trevor crash-lands on their island Themyscira and informs her about it.', 'https://images.alphacoders.com/724/thumb-350-724109.jpg', 'https://wallpaperaccess.com/full/167747.jpg', 'Gal Gadot', 'DC', 'Wonder woman'),
(25, 'Hal Jordan', 'The film tells the story of Hal Jordan, a test pilot who is selected to become the first human member of an intergalactic police force called the Green Lantern Corps. Hal is given a ring that grants him superpowers, and must confront Parallax, who threatens to upset the balance of power in the universe', 'https://wallpaperaccess.com/full/459472.jpg', 'https://www.teahub.io/photos/full/280-2806329_green-lantern.jpg', 'Ryan Reynolds', 'DC', 'Green Lantern'),
(26, 'Barry Allen', 'The Flash, a costumed superhero crime-fighter with the power to move at superhuman speeds. It is a spin-off from Arrow, existing in the same fictional universe known as Arrowverse. The series follows Barry Allen, portrayed by Grant Gustin, a crime scene investigator who gains super-human speed, which he uses to fight criminals, including others who have also gained superhuman abilities.', 'https://wallpapercave.com/wp/wp3739535.jpg', 'https://wallpaperbat.com/img/389729-the-flash-4k-wallpaper-top-free-the-flash-4k-background.jpg', 'Grant Gustin', 'DC', 'Flash'),
(27, 'Arther Curry', 'Arthur Curry / Aquaman, who sets out to lead the underwater kingdom of Atlantis and stop his half-brother, King Orm, from uniting the seven underwater kingdoms to destroy the surface world. Amber Heard, Willem Dafoe, Patrick Wilson, Dolph Lundgren, Ludi Lin, Yahya Abdul-Mateen II, Temuera Morrison and Nicole Kidman appear in supporting roles.', 'https://freeaddon.com/wallpaper/aquaman/thumb444x250-01.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWAApb3BTDepuyNOQnF-9QZSUFDl--B7lyuXgOv3u37hKnPpozhvMeMzKQmsY81wJhT8c&usqp=CAU', 'Jason Momoa', 'DC', 'Aquaman'),
(28, 'Victor Stone', 'Victor Stone is the son of Silas Stone and Elinore Stone, scientists who use him as a test subject for various intelligence enhancement projects. While these treatments are ultimately successful and Victor\'s IQ subsequently grows to genius levels, he grows to resent his treatment.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO2W1cc6r6E3mCmihVF_stsM0GNC5DiGgoL_PuusyFyO3OnDmodVeLbqRzEFbnXozijq0&usqp=CAU', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA6-JgUdSI9MSWPh_frIlqrO5O0ylVcm6jRFUiS3nHEFPnwJxIQYR26wRIHyg8rLj_l2E&usqp=CAU', 'Ray Fisher', 'DC', 'Cyborg'),
(29, 'Dinah Drake Lance', 'One of DC\'s earliest superheroines, the title Black Canary has appeared in many of the company\'s flagship team-up titles, including Justice Society of America and Justice League of America. Since the late 1960s, the character has been paired with archer superhero the Green Arrow, both professionally and romantically. As well as featuring in many Green Arrow stories, she is closely associated with the Batman family of characters, and specifically Barbara Gordon, her best friend, with whom she leads the superhero team Birds of Prey', 'https://vistapointe.net/images/black-canary-2.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQh0_wBCVzA3XxmsrrXiOm-4rlQlGwrce56E_bIABrBUHHprsr2JfOykUbpwBVlQPmHio&usqp=CAU', 'Katie Cassidy', 'DC', 'Black Canary'),
(30, 'Leonard Snart', 'Captain Cold (Leonard Snart) is a supervillain appearing in American comic books published by DC Comics. He is the leader of the Rogues, a loose criminal association, as well as the older brother of Golden Glider. An adversary of the various superheroes known as the Flash, he has served as one of Barry Allen\'s archenemies, both adversary and begrudging ally of Wally West, and one of the killers of Bart Allen.[3] As part of 2011\'s The New 52 reboot, Captain Cold and his team live by a code to never kill.', 'https://wallpapercave.com/wp/wp1965267.jpg', 'https://s.itl.cat/pngfile/s/6-67894_destiny-wallpaper-elegant-hunter-wallpaper-destiny-destiny-2.png', 'Wentworth Miller', 'DC', 'Captain Cold'),
(31, 'Ruby Rose', 'It follows Kate Kane, the cousin of vigilante Bruce Wayne, who becomes Batwoman in his absence. Beginning with the second season, the series focuses on former convict Ryan Wilder as she protects Gotham City in the role of Batwoman', 'https://www.teahub.io/photos/full/272-2722123_batwoman-cw.jpg', 'https://i.pinimg.com/736x/cf/af/fc/cfaffc04ea08e2e992b298ba215edf91.jpg', 'Ruby Rose', 'DC', 'Batwoman'),
(32, 'Selina Kyle', 'Catwoman is a Gotham City burglar who typically wears a tight, one-piece outfit and uses a bullwhip for a weapon. She was originally characterized as a supervillain and adversary of Batman, but she has been featured in a series since the 1990s which portrays her as an antiheroine, often doing the wrong things for the right reasons. The character thrived since her earliest appearances, but she took an extended hiatus from September 1954 to November 1966 due to the developing Comics Code Authority in 1954. These issues involved the rules regarding the development and portrayal of female characters that were in violation of the Comics Code, a code which is no longer in use. In the comics, Holly Robinson and Eiko Hasigawa have both adopted the Catwoman identity, apart from Selina Kyle.', 'https://c4.wallpaperflare.com/wallpaper/855/805/218/halle-berry-catwoman-4k-wallpaper-preview.jpg', 'https://i.pinimg.com/originals/67/6f/5d/676f5d25e25b17cef6665a49b755e04f.jpg', 'Anne Hathaway', 'DC', 'Catwoman'),
(33, 'Ronnie Raymond, Martin Stein, Jason Rusch', 'Ronnie Raymond and Martin Stein fused together debuted as the first incarnation in Firestorm, the Nuclear Man #1 (March 1978) and were created by Gerry Conway and Al Milgrom.[1][2] Jason Rusch debuted as a modern update of the character in Firestorm (vol. 3) #1 (July 2004), and was created by Dan Jolley and ChrisCross.', 'https://wallpaperaccess.com/full/1080170.jpg', 'https://wallpaperaccess.com/full/1080169.jpg', 'Franz Drameh', 'DC', 'Firestorm'),
(34, 'Grodd', 'He is an evil, super-intelligent gorilla who gained mental powers after being exposed to a strange meteorite\'s radiation', 'https://c4.wallpaperflare.com/wallpaper/490/179/817/injustice-injustice-2-gorilla-grodd-wallpaper-preview.jpg', 'https://i0.wp.com/the-avocado.org/wp-content/uploads/2019/11/Flashpoint_Grodd_of_War_Vol_1_1_Textless-625x352.jpg?fit=625%2C352&ssl=1', 'David Sovolov', 'DC', 'Gorilla Grodd'),
(35, 'Oliver Jonas Queen', 'Oliver Jonas Queen, a wealthy businessman and owner of Queen Industries who is also a well-known celebrity in Star City. He uses this position to hide the fact that he is the Arrow.[1] Sometimes shown dressed like the character Robin Hood, Green Arrow is an archer who uses his skills to fight crime in his home cities of Star City and Seattle, as well as alongside his fellow superheroes as a member of the Justice League', 'https://wallpaperaccess.com/full/2381768.jpg', 'https://pbs.twimg.com/media/EqmzD8QXIAEZVB-.jpg', 'Stephen Adam Amell', 'DC', 'Green Arrow'),
(36, 'Harleen Frances Quinzel', 'Quinn\'s origin story features her as a former psychiatrist at Gotham City\'s Arkham Asylum named Dr. Harleen Quinzel who fell in love with the Joker, her patient, eventually becoming his accomplice and lover. The character\'s alias is a play on the stock character Harlequin from the 16th-century theater commedia dell\'arte', 'https://images.hdqwalls.com/wallpapers/margot-robbie-harley-29.jpg', 'https://images.hdqwalls.com/wallpapers/harley-quinn-bosslogic-qr.jpg', 'Margot Robbie', 'DC', 'Harley Quinn'),
(37, 'Carter Hall', 'Hawkman is most often depicted as human archaeologist Carter Hall—the modern-day reincarnation of an ancient Egyptian prince named Khufu—or as alien police officer Katar Hol from the planet Thanagar. The character is generally regarded as having one of the most confusing backstories of any in DC Comics, due to a series of reinventions over the years following DC\'s 1985 series Crisis on Infinite Earths. Some writers have attempted to integrate Carter Hall and Katar Hol into one story by linking the Thanagarian aliens to the Egyptian curse that causes Hawkman to reincarnate periodically throughout human history, or by using Carter Hall as Katar Hol\'s alias, or otherwise depicting the merger of Carter and Katar into one being', 'https://images.hdqwalls.com/wallpapers/hawkman-sq.jpg', 'https://www.desktopbackground.org/download/3840x2400/2015/03/22/921358_30-hawkman-hd-wallpapers_5400x3037_h.jpg', 'Falk Hentschell', 'DC', 'Hawkman'),
(38, 'Iris West Allen', 'She has been the main love interest and later wife of Barry Allen, the alter ego of the Silver Age version of the superhero The Flash, and the aunt and grandmother, respectively, of the Modern Age variations of the characters Wally West and Bart Allen', 'https://www.denofgeek.com/wp-content/uploads/2021/07/FLA718fg_0004r.jpg?resize=768%2C432', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR40DKEvyI7bhNcMYlZA0MXSgG-PqloJ_R7Lg&usqp=CAU', 'Candice Patton', 'DC', 'Iris West'),
(39, 'Wally West', 'After Wally West had made a name for himself as the new Flash, the character of Bart Allen, grandson of the second Flash Barry Allen, was brought into the past from his home in the future and served as the young hero Impulse. In 2003, with writer Geoff Johns\' relaunch of a new Young justice volume, Bart donned the mantle of Kid Flash after being nearly killed by the assassin Deathstroke. Following a 2011 reboot, DC introduced a new interpretation of Wally West as its latest Kid Flash in 2014, who was later established as being the original Wally\'s younger cousin Wallace West.', 'https://www.looper.com/img/gallery/is-kid-flash-replacing-firestorm-on-legends-of-tomorrow/intro-1516304016.jpg', 'https://www.geekgirlauthority.com/wp-content/uploads/2016/07/kidflash.jpg', 'Keiynan Lonsdale', 'DC', 'Kid Flash'),
(40, 'Stefan Salvatore', 'Stefan Salvatore was one of the two main male protagonists of The Vampire Diaries. Stefan was a 171-year-old cured vampire and the distant descendant and doppelgänger of Silas. Stefan was born and raised in the supernatural town of Mystic Falls, Virginia and came of age during the time of the Civil War. Stefan was the youngest child of Giuseppe Salvatore and Lillian Salvatore. He had an older brother, Damon Salvatore, who is also a cured vampire and whom he shared a strained relationship with, stemming from the appearance of Katherine Pierce over whom they fought whilst human. Both brothers had same love interests which was Katherine and Elena gilbert, eventually Katherine chose Stefan but betrayed later, later Stefan fell in love with Caroline and married her. Elena chose Stefan at first and later went on having romantic relationship with Damon Salvatore and married him.', 'https://i.pinimg.com/564x/6e/79/cf/6e79cf18f6dd1a327f9264c0d307dcf5.jpg', 'https://i.pinimg.com/564x/35/e4/e2/35e4e2a8301f511ab6856a0750b5f8c2.jpg', 'Paul Wesley', 'VD', 'Vampire/Human'),
(41, 'Damon Salvatore', 'Damon Salvatore is one of the two main male protagonists of The Vampire Diaries. Damon was a 178-year-old vampire. Since his younger brother, Stefan Salvatore, injected him with the Cure, he is now human. He was a major antagonist in the first part of Season One. He was born in 1839 and lived in the colonial town of Mystic Falls with his brother Stefan, his father, Giuseppe Salvatore, and also with his mother Lillian Salvatore until her death in 1858. He became a vampire in 1864. At the time of his return to Mystic Falls, Damon and Stefan hadn\'t seen each other in fifteen years due to their bitter and violent relationship. Later on, their bond eventually improved just like the olden times and swore to each other that they will always protect each other and have each other’s Backs.', 'https://i.pinimg.com/564x/12/c7/d8/12c7d83dc94c103e151525924f10a5e9.jpg\r\n', 'https://i.pinimg.com/564x/db/41/c2/db41c2a8292bd97e1e0c39598f646712.jpg', 'Ian joseph Somerhalder', 'VD', 'Vampire/Human'),
(42, 'Elena Gilbert Salvatore', 'Elena Gilbert Salvatore, The main female protagonist of The Vampire Diaries. At the beginning of the series, Elena appears to be a regular human girl, but is then revealed to be a Petrova doppelgänger. Elena had been struggling to live a normal life ever since her adoptive parents, Miranda and Grayson Gilbert, died in a car accident when she was seventeen years old. Her life also changed drastically as she and her friends are caught up in the supernatural world that surrounds them and are forced to face powerful supernatural enemies.\r\nElena was described as a star student. She was popular, sporty, smart, compassionate, empathetic, caring and friendly. In the Season Three finale, she became a vampire despite never wanting to be one. In I\'d Leave My Happy Home For You, she takes the Cure to become human again\r\n', 'https://i.pinimg.com/564x/be/df/2a/bedf2a7c6159d3fe459ba28667c36f78.jpg\r\n', 'https://i.pinimg.com/564x/03/9f/b1/039fb1279a1bd9898a490e8e33fb7698.jpg\r\n', 'Nina Dobrev', 'VD', 'Human/Vampire'),
(43, 'Katherine Pierce/Pethrova', 'Katherine Pierce, born Katerina Petrova was a witch of the Traveller sub-culture and a former main character of The Vampire Diaries. She was also the second-known Petrova Doppelgänger of Amara and a former vampire. She was the main antagonist of season one (mostly off-screen through John Gilbert\'s and Isobel\'s actions, as both were working for her in order to kill off the tomb vampires), and one of the main antagonists of season two, the second half of season four and the first half of Season Five. She was also the final antagonist of season eight. Katherine can be considered the main antagonist of the series overall due to being a major antagonist in the first, second, fourth , fifth and eight seasons and all the antagonists that were a result of her actions.', 'https://i.pinimg.com/564x/8b/f4/66/8bf466f446897a3a37a70df1afcd27d0.jpg\r\n\r\n', 'https://i.pinimg.com/564x/c4/ff/72/c4ff728d1de8c88e037e24f270f6024c.jpg', 'Nina Dobrev', 'VD', 'Vampire/Human'),
(44, 'Caroline Forbes Salvatore', 'Caroline Elizabeth Forbes-Salvatore is a vampire and one of the main female characters on The Vampire Diaries. Caroline is the daughter of William Forbes II and Sheriff Elizabeth Forbes, the wife of the late Stefan Salvatore and the sister-in-law of Damon Salvatore and Elena Gilbert. She is also the surrogate mother of Alaric and Jo\'s twin daughters, Lizzie and Josie Saltzman. Prior to her transition into a vampire, she was known for her insecurities, which caused her to be excessively competitive, mainly with Elena. And later became the most loving and favourite character’s for her good nature. Her character attracted a wide audiences and also the ship Klaroline which was Klaus and Caroline', 'https://i.pinimg.com/564x/08/ac/ee/08aceeebe7f29d93c5b32b13de3bf93a.jpg', 'https://i.pinimg.com/564x/d7/d9/6f/d7d96fb4a74f79f7db9eea03128bb9a3.jpg\r\n', 'Candice King', 'VD', 'Vampire'),
(45, 'Bonnie Bennett', 'Bonnie Bennett is a very powerful witch and one of the main female characters of The Vampire Diaries. While she filled the role of counsellor and confidante to all of her friends, Bonnie is a feisty, yet empathetic witch, who discovered her powers just in time to help out her family and friends. She is best friends with Caroline Forbes, Elena Gilbert, Matt Donovan, Damon Salvatore, and her ex-boyfriend, Jeremy Gilbert and has known most of them since childhood. She is also close friends with Stefan Salvatore and Tyler Lockwood. Bonnie was in a romantic relationship with Lorenzo St. John before his death.', 'https://i.pinimg.com/564x/2e/e0/72/2ee0722d3b27aa32091592953546182c.jpg', 'https://i.pinimg.com/564x/66/01/e3/6601e342bb0ed375dbba9aa8578bdbbb.jpg\r\n', 'Kat Graham', 'VD', 'Witch'),
(46, 'Tyler Lockwood', 'Tyler Lockwood was a former main character, protagonist, current werewolf and a former hybrid on The Vampire Diaries, who played for the football team at Mystic Falls High School. Tyler was also an antagonist/anti villain of the episode Bloodletting of The Originals, where Tyler carried out his vendetta against the infamous Klaus Mikaelson.\r\nInitially after becoming a hybrid, he was extremely grateful to Klaus for taking away his pain of turning every month. However, he soon becomes angered at the prospect of being sired to him. He manages to break the sire bond and continued to help other hybrids break the curse of being sired. This came at a price once Klaus found out about his actions, as Klaus murdered his mother and last remaining family member. Since then, he swore revenge on Klaus for his actions. In the end he dies as werewolf\r\n', 'https://i.pinimg.com/564x/6f/6e/66/6f6e66626e7ab024285eadc26caeb53c.jpg\r\n', 'https://i.pinimg.com/564x/09/b2/3f/09b23f575f526e5f7cc8abceb8fe48c0.jpg\r\n', 'Michael Anthony Trevino', 'VD', 'Werewolf and First Klaus\'s Hybrid'),
(47, 'Jeremy Gilbert', 'Jeremy Gilbert is a former main character and a male protagonist on The Vampire Diaries. Jeremy is the adoptive brother and biological cousin of Elena Gilbert, as well as a former medium, although this status became defunct following the collapse of the Other Side. He is also a member of the Brotherhood of the Five. His best friends are Matt Donovan, Tyler Lockwood, and Bonnie Bennett, who was also his girlfriend. Following his resurrection in the Season Four finale, he moved into the Salvatore Boarding House with his sister and her boyfriend, Damon Salvatore since their house was burned Elena after Jeremy\'s death. However, he moved out of the boarding house halfway through Season Five and moved into the Lockwood Mansion with Matt and Tyler.', 'https://i.pinimg.com/564x/86/76/c0/8676c09604ee909b2aa6b3a39124bac9.jpg\r\n', 'https://i.pinimg.com/564x/0b/0d/f5/0b0df51c709945bf3723feed7d475c68.jpg', 'Steven McQueen', 'VD', 'Hunter'),
(48, 'Matt Donovan', 'Matthew G. (Matt) Donovan is a main character on The Vampire Diaries and a guest character in the third season of The Originals and first season of Legacies. He is the son of Kelly Donovan and Peter Maxwell. He had an older sister Vicki Donovan, who was turned into a vampire, and was later killed because she was unable to control her blood lust. Matt is also the ex-boyfriend of Elena Gilbert, Caroline Forbes and Rebekah Mikaelson and former fiancé of Penny Ares. He is currently working for the sheriff department at Mystic Falls.', 'https://i.pinimg.com/564x/8c/9b/9f/8c9b9f73d260253b9108b8b90ebef98d.jpg\r\n', 'https://i.pinimg.com/564x/7a/83/47/7a8347b887e90334c32a7d64f1e2c437.jpg\r\n', 'Zachary George Roerig', 'VD', 'Human'),
(49, 'Dr. Alaric Saltzman', 'Alaric “Ric\" Saltzman is a main character of The Vampire Diaries and Legacies. He is a former recurring character of the first half of Season One, Season Four and Season Five. He was also a recurring character on The Originals. Alaric is a human, vampire hunter, former history teacher at Mystic Falls High School and a former Enhanced Original, not by being one of the first vampires as the Mikaelson Family is, but instead being turned through an altered version of the spell used on the Mikaelson family. He originally came to Mystic Falls to find the vampire who killed his wife, but learned that she voluntarily became a vampire and left him. He also learned that his wife had a child when she was a teenager, a daughter named Elena Gilbert, his student.', 'https://i.pinimg.com/564x/cc/e9/cf/cce9cf4cac164731918713b137f6450b.jpg\r\n', 'https://i.pinimg.com/564x/ed/58/4d/ed584d6c9d3873f480ed4e2b15cfc1ce.jpg\r\n', 'Matthew W. Davis', 'VD', 'Hunter/Human'),
(50, 'Lorenzo St. John', 'Lorenzo (Enzo) St. John was a main character, minor antagonist, and anti-hero in The Vampire Diaries. He was formerly a major recurring character in the fifth season of the series, before being promoted to main in the sixth season. He was a vampire who was previously Damon Salvatore\'s cellmate in the 1950s, after being captured by the Augustine’s. He was first mentioned by Dr . Wes Maxfield, being dubbed as the Augustine Vampire.\r\nHe then falls in love with Bonnie and will be in a romantic relationship with her, After his death, Enzo remains with Bonnie after she created her own dimension and he helps her with her grief and anger towards Stefan for killing him. This culminates in Bonnie letting go of Enzo, at his request, to save Lizzie, Josie and herself. In a flash-forward, he watches over her as she begins packing to travel the world.\r\n', 'https://i.pinimg.com/564x/ef/48/e4/ef48e4024ba43dac186e4187d02c6429.jpg\r\n', 'https://i.pinimg.com/564x/d7/64/1a/d7641a8de96c8a8551e032e57681eb7e.jpg\r\n', 'Michael Malarkey', 'VD', 'Vampire'),
(51, 'Kai parker', 'Kai Parker is the main antagonist of Season 6 of The Vampire Diaries and a major antagonist in Legacies. He is a young warlock with the unnatural power to siphon magic. Because of this power, and the fact he murdered his siblings, Kai was considered an abomination.', 'https://i.pinimg.com/564x/61/49/13/614913164971228932ce390056b9f2e6.jpg\r\n', 'https://i.pinimg.com/564x/a1/c3/79/a1c379d83bee0117f80d8fa47f44e799.jpg\r\n', 'Chris wood', 'VD', 'Witch'),
(52, 'Josette (Jo) Laughlin (born Parker) ', 'Dr Josette (Jo) Laughlin (born Parker) was a character who first appeared in the first episode of the sixth season in The Vampire Diaries. She was a witch of the Gemini Coven, daughter of Joshua Parker, twin sister to Kai and elder sister to Joey, Liv and Luke. She relinquished her magic into a knife to prevent Kai from merging with her, and, as a non-practicing witch, became a doctor at Whitmore Hospital.\r\nJO regained her powers after being given incentive by Kai, who escaped the 1994 Prison World that she had helped trap him in; however, Luke merged with him instead, resulting in Luke\'s death. Although she loathed Kai for destroying her family, she agreed to help him with his post-merge sickness by transferring her magic to him, considering the whole coven would die if he did. She later learned that she was pregnant with Alaric Saltzman\'s children, and the two immediately decided to wed. However, Jo was killed by Kai at their wedding.\r\n', 'https://i.pinimg.com/736x/56/98/2a/56982acdb2df7f14edfd82805e481c2b.jpg\r\n', 'https://i.pinimg.com/564x/dc/5f/3c/dc5f3ccd40ee32c2127524631d928847.jpg\r\n', 'Jodi Lyn O\'Keefe', 'VD', 'Witch'),
(53, 'Lexi Brason', 'Alexia \"Lexi\" Branson was a character who first appeared in the eighth episode of the first season in The Vampire Diaries. She was a vampire and was also Stefan Salvatore\'s best friend and companion. She had known Stefan and his brother Damon for over a century. Damon killed her to make the Town Council think that she was the vampire terrorizing Mystic Falls. She was 350 years old, placing her birth date around 1659 and her turning year in 1680.\r\nIn season 5, she returns in Home, and saves Stefan from going into Hell, but she manages to find peace and disappears. She continues to watch over him and greets him when he too dies in I Was Feeling Epic.', 'https://i.pinimg.com/564x/78/76/2f/78762f619f867e4e575abd83eb5ebf66.jpg\r\n', 'https://i.pinimg.com/564x/6c/69/77/6c69771409f093f13476ed60c7ebac7e.jpg\r\n', 'Arielle Kebbel', 'VD', 'Vampire'),
(54, 'Niklaus Mikaelson', 'Niklaus Mikaelson was the main protagonist (and sometimes antagonist/anti-hero) of The Originals. He was a former main character, antagonist/anti-hero of The Vampire Diaries. Klaus was an Original vampire and a werewolf, making him the Original Hybrid.\r\nKlaus was the biological son of Ansel and Esther Mikaelson, the step-son of Mikael, and nephew of Dahlia. Klaus is the maternal younger half-brother of Freya, Finn, Elijah, and the maternal older half-brother of Kol , Rebekah and Henrik Mikaelson. Klaus was the uncle of Freya and Mathias\' unborn son and Freya and Keelin\'s son. Klaus is the father of hope, whose mother is Hayley, and the adopted father of Marcel Gerard, an orphan boy he rescued and eventually turned into a vampire.\r\n', 'https://i.pinimg.com/564x/c9/ce/84/c9ce844e6093e2864095566dabb0123d.jpg\r\n', 'https://i.pinimg.com/564x/08/8b/7a/088b7aa702b81cbee95c92faf9df0846.jpg\r\n', '', 'VD', 'Original Vampire and werewolf  First Hybrid '),
(55, 'Elijah Milkelson', 'Elijah Mikaelson was the deuterogamist of The Originals. He was formerly a major recurring character in The Vampire Diaries, serving initially as an antagonist in the second season and eventually becoming a supporting character and protagonist in the third season and fourth seasons. Elijah was an Original Vampire.\r\nElijah was the third child and second son of Mikael and Esther. He was the younger brother of Freya and Finn, and the older brother of Kol, Rebekah and Henrik and the older half-brother of Klaus. He is also the uncle of Freya and Mathias\' unborn son, Klaus and Hayley\'s daughter, Hope, and Freya and Keelin\'s son, Nik.\r\n', 'https://i.pinimg.com/564x/1d/86/15/1d86151cc19005997965d5b08a3763ec.jpg\r\n', 'https://i.pinimg.com/564x/e8/44/26/e844262bec2de5005d5e692c47cd3a29.jpg', 'Daniel Gillies', 'VD', 'Original Vampire  First among 5 Original Vampires'),
(56, 'Rebekah Mikaelson', 'Rebekah Mikaelson is the former female protagonist of The Originals. She was a major recurring and guest character in the third, fourth and fifth seasons of The Vampire Diaries. She is the sole female Original vampire.\r\nThroughout her millennium-long life, Rebekah\'s actions and personality have been heavily influenced by her relationship with Klaus and her desire to live a normal, human life. She has also been romantically involved with a few characters from the series. In the 12th century, she was in love with a Vampire Hunter named Alexander who was a member of the Brotherhood of the Five. In the late 19th and early 20th century, she was in a relationship with Klaus\' protégé Marcel Gerard while she and her family lived in New Orleans. After she fled New Orleans with Klaus to escape her father Mikael, she was briefly in a\r\nRelationship with Stefan Salvatore in Chicago during the early 1920s, and because she chose Stefan over her half-brother, Klaus daggered her for ninety years in pun', 'https://i.pinimg.com/564x/2b/c1/ff/2bc1ffc72ef48172df756c4cc09f4d13.jpg\r\n', 'https://i.pinimg.com/564x/24/1e/23/241e23f2ffb7a8fd6e6d84a5cc0262f4.jpg\r\n', 'Clarie Holt', 'VD', 'Original Vampire  First Among 5 Original Vampires'),
(57, 'Kol Mikaelson', 'Kol Mikaelson is a major recurring character on The Originals. He also had a recurring role in the third, fourth and fifth season of The Vampire Diaries, where he served as an antagonist and anti-hero. Kol is also the main protagonist of the short web series The Originals: The Awakening.', 'https://i.pinimg.com/564x/07/dd/8d/07dd8df1ade5cdd5b830ce55dd0baa5c.jpg\r\n', 'https://i.pinimg.com/564x/e4/37/1d/e4371d68212cead1d03fc68f1e823b8e.jpg\r\n', 'Nathenial Buzolic', 'VD', 'Original Vampire  First among 5 Original Vampires'),
(58, 'Freya Mikaelson', 'Freya is the firstborn child of Mikael and Esther, the elder sister of Finn, Elijah, Kol, Rebekah, and Henrik, the maternal older half-sister of Klaus. She is the paternal aunt of Klaus and Hayley\'s daughter, Hope. She is the bereaved mother of her and with Mathias\' unborn son. Freya is also the wife of Keelin and the mother of their son, Nik.\r\n\r\n', 'https://i.pinimg.com/564x/e8/43/41/e8434123ea15772f991eee98e384d713.jpg\r\n', 'https://i.pinimg.com/564x/c9/d4/fa/c9d4fa6b41042d86078c9241225b1d56.jpg\r\n', 'Riley Voelkel', 'VD', 'Original Witch'),
(59, 'Finn Mikaelson', 'Finn Mikaelson was a major recurring character on The Originals. He served as the primary antagonist for most of the second season. Finn also had a recurring role in the third season of The Vampire Diaries, where he served as a minor antagonist and anti-villain.\r\nFinn was the first son and second child of Mikael and Esther. He was the younger brother of Freya, and the older brother of Elijah, Kol, Rebekah, and Henrik and the older half-brother of Klaus. He is also the uncle of Freya and Mathias\' unborn son, Klaus and Hayley\'s daughter, Hope, and Freya and Keelin\'s son, Nik.\r\n', 'https://i.pinimg.com/564x/19/52/b1/1952b14ad2128aaa52fd76651b39df79.jpg\r\n', 'https://i.pinimg.com/564x/db/03/ff/db03ff8627859b9b42fd00f63ce84bef.jpg\r\n', 'Casper zafer', 'VD', 'Original Vampire'),
(60, 'Clary Fairchild', 'Clarissa \"Clary\" Adele Fairchild, also known as Clary Fray, is the Shadowhunter daughter of Jocelyn Fray and the notorious Valentine Morgenstern. For years, Clary lived a mundane life with Jocelyn, until the return of her father and her brother, Jonathan, exposed her to a new world, throwing their lives out of balance as Clary found herself on a journey with her fellow Shadowhunters to stop them.\r\nAs a result of her father\'s experiments, Clary possesses more angel blood than other Shadowhunters and, through this, the ability to recall powerful, ancient runes not written in the Gray Book\r\n', 'https://i.pinimg.com/564x/f0/9f/f2/f09ff2aed0b4e566f961a6c30a08ccc5.jpg\r\n\r\n', 'https://cdn1.edgedatg.com/aws/v2/abcf/Shadowhunters/video/202/9f0bdf9a6b3a5c27bcbfcb725d0677df/579x325-Q100_9f0bdf9a6b3a5c27bcbfcb725d0677df.jpg', 'Katherine McNamara', 'MI', 'Clary Fray'),
(61, 'Jace Herondale', 'Jace was born to Stephen and Céline Herondale. While he was still in Céline\'s womb, Valentine Morgenstern constantly gave Céline doses of Ithuriel\'s blood to mix with her food, and she took it, not knowing what it really was. Ithuriel\'s blood made its way into unborn baby Jace\'s system, thus he was born differently from other Shadowhunters.\r\nJace was raised by Valentine believing that they were the Waylands, and they lived in the Waylands\' estate. Jace\'s upbringing was both loving and harsh; Valentine trained him as a warrior. Jace became good friends with the Lightwood children, Alec and Isabelle Lightwood. The eldest, Alec, eventually became his parabatai. The youngest, Max, grew to look up to Jace.', 'https://64.media.tumblr.com/21af6a6263c410deec0a77aaa2ea7560/407d4a6d3b461c1e-6e/s500x750/31a6c6590b915d5eec9c77c4660f465c3de8c3bd.png\r\n', 'https://64.media.tumblr.com/0394fe03d6ec6561d1daa32b2a5fe11d/9ba39036f33b5340-de/s540x810/3f00e38cb6cf4e02aaed5a4c0dda31231bfb21d2.jpg\r\n', 'Dominic Sherwood', 'MI', 'Jace Herondale'),
(62, 'Simon Lewis', 'Simon Lovelace, born Simon Lewis, is Clary Fairchild\'s best friend and parabatai and Isabelle Lightwood\'s fiancé. A mundane when he was originally introduced to the Shadow World, Simon was once turned into a vampire, and later to a Daylighter. He is a hero of the Mortal and Dark wars. After a turn of events, Simon\'s immortality was taken away, along with his memories. To help him regain these memories, Simon Ascended and became a Shadowhunter himself', 'https://i.pinimg.com/170x/25/06/99/250699df99fc1f373fbca831c3088ee8.jpg\r\n', 'https://i.pinimg.com/originals/d0/43/33/d0433381801866866ee7cf5b39948a7f.jpg\r\n', 'Alberto Rosende', 'MI', 'Simon Lewis'),
(63, 'Isabelle Lightwood', 'Isabelle Sophia Lightwood is a Shadowhunter currently under the New York Conclave. She is the only daughter of Robert and Maryse Lightwood, the sister of Alec and Max, and the adoptive sister of Jace Herondale. She was about nine years old when Jace Wayland was adopted into their family. Hearing from her mother that Jace had witnessed the death of his own father, Isabelle, who liked the feeling of being wanted, had expected Jace to come to her like a scared child needing comfort. Instead, she was disappointed when Jace turned out to be independent, brave and seemingly self-possessed, among other traits that slightly reminded Isabelle of herself. Eventually, when Jace made it clear that he saw Isabelle as a possible training partner and equal, she grew to love him as a brother.', 'http://pm1.narvii.com/6403/ddc762d911553f437f24b9bf640e9476c738eb47_00.jpg', 'https://pbs.twimg.com/profile_images/1134902414853705729/Tuf425If_400x400.jpg\r\n', 'Emeraude Toubia', 'MI', 'Isabelle Lightwood'),
(64, 'Alec Lightwood', 'Alexander \"Alec\" Gideon Lightwood-Bane, or simply known as Alec Lightwood, is a Shadowhunter and the current Consul of the  Clave. He is the husband of Magnus Bane, is the adoptive father of Rafael and Max Lightwood-Bane, and is the older brother of Isabelle and Max, as well as the adoptive brother and parabatai of Jace Herondale.\r\nAlec is one of the few openly gay Shadowhunters', 'https://pbs.twimg.com/profile_images/819530104632201220/c25TArVX_400x400.jpg', 'https://ladygeekgirl.files.wordpress.com/2017/04/shadowhunters-alec.jpg\r\n', 'Matthew Daddario', 'MI', 'Alec Lightwood'),
(65, 'Magnus Bane', 'Magnus was born to a half-Dutch and half-Indonesian woman and the Prince of Hell, Asmodeus in the 17th century in Jakarta, Indonesia, back then known as Batavia of the Dutch East Indies. He was born seemingly normal, only with unusual amber eyes.\r\nMagnus Bane is the High Warlock of Brooklyn. Being over four centuries old, his life has since intertwined with several Shadowhunters and Downworlders over the centuries. As of 2012, he is the husband of Consul Alec Lightwood and the adoptive father of Rafael and Max Lightwood-Bane.\r\n', 'https://pbs.twimg.com/profile_images/1414608417671499776/WxghzShV_400x400.jpg\r\n', 'https://eachpage.files.wordpress.com/2019/05/magnus-bane-edom.jpg?w=1200\r\n', 'Harry Shum Jr.', 'MI', 'Magnus Bane');
INSERT INTO `characters` (`id`, `name`, `description`, `image1`, `image2`, `played_by`, `universe`, `uni_char`) VALUES
(66, 'Valentine Morgenstern', 'Valentine Morgenstern was the husband of Jocelyn Fray, and the father of Sebastian and Clary. An advocate against Downworlders, Valentine led the Circle with the main goal of ridding the world of them. After his initial failure, his new objective became the reformation of the Shadowhunters as a whole. He was born to Oskar and Seraphina Morgenstern. Seemingly from a wealthy family, he was raised in Idris and spent his childhood in a valley not far from Lake Lyn. His father raised him as a warrior, causing Valentine to both hate and love him. When he was old enough, Valentine attended the Shadowhunter Academy in Alicante and excelled. His good looks, charisma and charm made him popular among both staff and fellow students.', 'https://cdn.quotesgram.com/img/74/8/1839839563-Valentine-Morgenstern-jonathan-rhys-meyers-33488520-500-640.jpg', 'https://bookstr.com/wp-content/uploads/2019/06/5c69ea85-7e79-4ea5-bfb6-a673e1089df2-300x158.jpg', 'Alan van Sprang', 'MI', 'Valentine Morgenstern'),
(67, 'Jocelyn Fairchild', 'Jocelyn Garroway (née Fairchild), also known as Jocelyn Fray, is the mother of Clary Fairchild and Jonathan Morgenstern, the wife of Luke Garroway and, formerly, Valentine Morgenstern.\r\nJocelyn was originally an active Shadowhunter and a member of the Circle with her then husband, Valentine Morgenstern, but after discovering her husband\'s heinous and cruel acts, she abandoned the cause and became a key orchestrator against the Uprising. Jocelyn escaped the life of Shadowhunters to live a safe mundane life in New York with her daughter, Clary. Jocelyn was born to Adele Nightshade and Granville Fairchild II. She grew up an only child in the Fairchild manor in Idris, where she developed a close friendship with Lucian Graymark, as well Lucian\'s older sister, Amatis\r\n', 'http://pm1.narvii.com/6561/6da5a587c175c3bc4e2b9135394b0c32581a9013_00.jpg\r\n', 'https://pm1.narvii.com/6782/0aad97d8d6a064f6bf7325b4599ad59202e1606cv2_hq.jpg\r\n', 'Lena Headey', 'MI', 'Jocelyn Fairchild'),
(68, 'Jonathan Morgenstern', 'Sebastian Morgenstern, born Jonathan Christopher Morgenstern, was the son of Valentine and Jocelyn, and the older brother of Clary Fairchild. As a result of experiments done on him by his father, Sebastian was a Shadowhunter born with demon blood. After a stint in Alicante when he posed as Sebastian Verlac, he decided to keep the name Sebastian as an act of defiance against his parents, though he reclaimed the name Jonathan during his last few moments without demon blood.', 'https://i.pinimg.com/originals/4f/bc/81/4fbc818f4f5fcfd701f02957506927da.png', 'https://pbs.twimg.com/profile_images/1320422754362019840/OcWoxOn-_400x400.jpg', 'Will Tudor', 'MI', 'Jonathan Morgenstern'),
(69, 'Luke Garroway', 'Luke Garroway, born Lucian Graymark, is the husband of Jocelyn Fray and the stepfather of, as well as the man who raised, her daughter, Clary. He is a werewolf who was formerly a Shadowhunter and a member of the Circle, before he was betrayed by his parabatai, Valentine Morgenstern', 'https://scatteredquotes.com/wp-content/uploads/2019/04/LukeGarroway-Quotes-Shadowhunters_1.jpg\r\n\r\n', 'https://www.williamjacket.com/wp-content/uploads/2019/09/Luke-Garroway-Shadowhunters-Leather-Jacket-main.jpg', 'Isaiah Mustafa', 'MI', 'Luke Garroway');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `characters`
--
ALTER TABLE `characters`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `characters`
--
ALTER TABLE `characters`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
